name: ðŸ› Bug Report
description: Report a bug or issue with IlliniHunt V2
title: "[BUG] "
labels: ["bug", "needs-clarification"]
projects: ["vishalsachdev/illinihunt"]
assignees:
  - vishalsachdev

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve IlliniHunt!

        ðŸ”§ **How it works**: @claude will analyze your bug report, implement a fix, and create a PR for review.

  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: Brief description of the issue
      placeholder: "Project cards not loading on mobile devices"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: How severe is this issue?
      options:
        - ðŸ”´ Critical (app crashes, data loss, security issue)
        - ðŸŸ¡ High (major feature broken, affects many users)
        - ðŸŸ  Medium (feature partially broken, workaround exists)
        - ðŸŸ¢ Low (minor issue, cosmetic problem)
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to 'https://illinihunt.vercel.app'
        2. Sign in with @illinois.edu account
        3. Navigate to 'Projects' page
        4. See error: [describe what happens]
    validations:
      required: true

  - type: textarea
    id: expected_vs_actual
    attributes:
      label: Expected vs Actual Behavior
      description: What should happen vs what actually happens?
      placeholder: |
        Expected: Project cards should load smoothly on mobile devices
        Actual: Project cards show loading spinner indefinitely or display error message
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you experiencing this issue?
      options:
        - Desktop - Chrome
        - Desktop - Firefox
        - Desktop - Safari
        - Desktop - Edge
        - Mobile - iPhone Safari
        - Mobile - Android Chrome
        - Tablet - iPad
        - Other (specify in additional context)
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other details that might help? (screenshots, console errors, etc.)
      placeholder: |
        - Screenshots or videos
        - Console errors (F12 > Console)
        - When did this start happening?
        - Any workarounds you found?

        Want AI fix? Add: @claude please fix this bug

  - type: markdown
    attributes:
      value: |
        ---

        ### ðŸ”§ Next Steps

        After submitting:
        1. We'll review and prioritize based on severity
        2. If you mentioned @claude, you'll get AI assistance
        3. We'll keep you updated on progress

        ### ðŸŽ“ Want to Help Fix It?

        Bug fixing is a great way to learn debugging and contribute to open source!