blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/vishalsachdev/illinihunt/discussions
    about: Ask questions, share ideas, or discuss features with the community
  - name: 📚 Contributing Guide
    url: https://github.com/vishalsachdev/illinihunt/blob/main/CONTRIBUTING.md
    about: Read our guide for contributors