name: 🎓 Course Project Integration
description: Connect your UIUC coursework with IlliniHunt contributions
title: "[COURSE] "
labels: ["course-project", "student-friendly"]
projects: ["vishalsachdev/illinihunt"]
assignees:
  - vishalsachdev

body:
  - type: markdown
    attributes:
      value: |
        Great! We welcome students who want to connect their coursework with real-world development.
        
        🚀 **How it works**: @claude can help scope your project and implement features for your coursework.

  - type: input
    id: course_info
    attributes:
      label: Course Information
      description: What course is this for?
      placeholder: "CS 465 - User Interface Design, Spring 2025, Prof. Smith"
    validations:
      required: true

  - type: dropdown
    id: course_code
    attributes:
      label: Course Code
      description: Select your course (or closest match)
      options:
        - CS 225 - Data Structures
        - CS 233 - Computer Architecture  
        - CS 411 - Database Systems
        - CS 465 - User Interface Design
        - CS 473 - Algorithms
        - CS 519 - Scientific Visualization
        - CS 527 - Computer Security
        - CS 591 - Advanced Topics
        - BADM 350 - Foundations of Business
        - BADM 554 - Business Intelligence
        - ECE 391 - Computer Systems Engineering
        - STAT 420 - Methods of Applied Statistics
        - Other (specify in project description)
    validations:
      required: true

  - type: dropdown
    id: project_type
    attributes:
      label: Project Type
      description: What kind of course project is this?
      options:
        - Final Project
        - Midterm Project
        - Weekly Assignment
        - Research Paper/Presentation
        - Group Project
        - Independent Study
        - Capstone Project
        - Extra Credit
    validations:
      required: true

  - type: textarea
    id: assignment_requirements
    attributes:
      label: Assignment Requirements
      description: What does your professor require?
      placeholder: |
        Example:
        - Build a web application feature
        - Write technical documentation
        - Present to class
        - Due: April 15, 2025
    validations:
      required: true

  - type: textarea
    id: proposed_contribution
    attributes:
      label: Proposed Contribution
      description: What would you like to work on?
      placeholder: |
        Example:
        - Improve the project submission form
        - Add new search filters
        - Create mobile-responsive components
        - Write technical documentation
    validations:
      required: true

  - type: dropdown
    id: timeline
    attributes:
      label: Project Timeline
      description: How long do you have to complete this?
      options:
        - 1-2 weeks
        - 3-4 weeks  
        - 5-8 weeks (half semester)
        - 9-16 weeks (full semester)
        - Flexible/ongoing
    validations:
      required: true

  - type: dropdown
    id: team_size
    attributes:
      label: Team Size
      description: Are you working alone or with others?
      options:
        - Individual (just me)
        - 2 people
        - 3 people
        - 4 people
        - 5+ people
    validations:
      required: true

  - type: textarea
    id: learning_goals
    attributes:
      label: Learning Goals
      description: What do you hope to learn?
      placeholder: |
        Example:
        - React and TypeScript development
        - Working with real codebases
        - Open source contribution process
        - Building portfolio projects

  - type: textarea
    id: deliverables
    attributes:
      label: Course Deliverables
      description: What do you need to submit?
      placeholder: |
        Example:
        - Working code implementation
        - Technical documentation
        - Class presentation
        - Project report

  - type: dropdown
    id: technical_skills
    attributes:
      label: Current Technical Skills
      description: What's your experience level?
      options:
        - Beginner (new to web development)
        - Some experience (built small projects)
        - Intermediate (comfortable with React/JS)
        - Advanced (professional or extensive experience)
        - Expert (could mentor others)
    validations:
      required: true

  - type: textarea
    id: support_needed
    attributes:
      label: Support Needed
      description: How can we help you succeed?
      placeholder: |
        Example:
        - Code review and feedback
        - Help understanding the codebase
        - Guidance on technical implementation
        - Mentorship and check-ins

  - type: dropdown
    id: professor_involvement
    attributes:
      label: Professor Involvement
      description: Is your professor aware of this integration?
      options:
        - Yes, professor suggested using open source project
        - Yes, professor approved this specific project
        - No, but professor is open to external projects  
        - No, need to get approval first
        - Not sure, need to discuss with professor
    validations:
      required: true







  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Anything else we should know?
      placeholder: |
        - Special requirements or constraints
        - Preferred communication methods
        - Timeline considerations
        
        Want AI help? Add: @claude please help with this course project

  - type: markdown
    attributes:
      value: |
        ---
        
        ### 🚀 Next Steps
        
        After submitting:
        1. We'll discuss project scope and feasibility
        2. Help you plan timeline and milestones
        3. Connect you with mentorship and resources
        
        ### 🎯 Benefits
        
        **For You:**
        - Real-world development experience
        - Portfolio project for applications
        - Modern tech stack experience
        
        **For IlliniHunt:**
        - Student perspectives and fresh ideas
        - Quality contributions to the platform