name: 🚀 Feature Request
description: Propose a new feature for IlliniHunt V2
title: "[FEATURE] "
labels: ["enhancement", "needs-clarification"]
projects: ["vishalsachdev/illinihunt"]
assignees:
  - vishalsachdev

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to improve IlliniHunt!

        🤖 **Want AI help?** Add `@claude` anywhere in your issue:
        - **Repository Collaborators**: Immediate automatic implementation and PR creation
        - **External Contributors**: AI guidance and assistance (requires workflow approval)

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: What feature would you like to see added?
      placeholder: "Add user notification system for new project submissions"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem This Solves
      description: What issue with IlliniHunt does this feature address?
      placeholder: |
        Example: Users miss new project submissions in categories they're interested in.
        They have to manually check the platform frequently to stay updated.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Example: Add a notification bell icon in the header that shows:
        - New projects in categories the user follows
        - Comments on projects they've voted on
        - Replies to their comments

        Users can mark notifications as read and configure preferences.
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature is?
      options:
        - 🟢 Simple (UI changes, small components)
        - 🟡 Moderate (new components, database changes)
        - 🔴 Complex (major features, architecture changes)
        - 🤔 Not sure
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other details that might help? (mockups, examples, timeline, etc.)
      placeholder: |
        - Similar features in other platforms
        - Screenshots or mockups
        - Technical considerations
        - Course project? Mention your course

        🤖 For automatic AI implementation, add: @claude please implement this feature

  - type: markdown
    attributes:
      value: |
        ---

        ### 🚀 Next Steps

        After submitting:
        1. **With @claude (Collaborators)**: Automatic implementation within minutes
        2. **With @claude (External Contributors)**: AI assistance after workflow approval
        3. **Without @claude**: Manual review and planning by the team

        ### 🎓 For Students

        Feature contributions are great for building your portfolio and learning modern web development!