name: 🚀 Feature Request
description: Propose a new feature for IlliniHunt V2
title: "[FEATURE] "
labels: ["enhancement", "needs-clarification"]
projects: ["vishalsachdev/illinihunt"]
assignees:
  - vishalsachdev

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to improve IlliniHunt! 
        
        🚀 **How it works**: @claude will ask clarifying questions, implement your feature, and create a PR for review.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: What feature would you like to see added?
      placeholder: "Add user notification system for new project submissions"
    validations:
      required: true

  - type: dropdown
    id: platform_area
    attributes:
      label: Platform Area
      description: Which part of the IlliniHunt platform does this feature improve?
      options:
        - User Interface & Design
        - Search & Discovery
        - Project Submission & Management
        - User Authentication & Profiles
        - Voting & Engagement
        - Comments & Community
        - Performance & Technical
        - Mobile Experience
        - Admin & Moderation
        - Analytics & Insights
        - Notifications & Alerts
        - API & Integrations
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Platform Issue or Need
      description: What issue with IlliniHunt does this feature address, or what need does it fulfill?
      placeholder: |
        Example: Users miss new project submissions in categories they're interested in. 
        They have to manually check the platform frequently to stay updated, which reduces engagement.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this platform feature to work?
      placeholder: |
        Example: Add a notification bell icon in the header that shows:
        - New projects in categories the user follows
        - Comments on projects they've voted on
        - Replies to their comments
        
        The feature should allow users to:
        - Mark notifications as read/unread
        - Configure notification preferences in settings
        - Optionally receive email summaries
    validations:
      required: true

  - type: dropdown
    id: user_type
    attributes:
      label: Target Users
      description: Who would benefit from this feature?
      multiple: true
      options:
        - Students (undergraduate)
        - Students (graduate)
        - Faculty
        - Staff
        - External visitors
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature is?
      options:
        - 🟢 Simple (UI changes, small components)
        - 🟡 Moderate (new components, database changes)
        - 🔴 Complex (major features, architecture changes)
        - 🤔 Not sure
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What needs to be done for this feature to be complete?
      placeholder: |
        - [ ] Notification bell icon appears in header for authenticated users
        - [ ] Badge shows unread notification count
        - [ ] Dropdown shows recent notifications with timestamps
        - [ ] Users can mark individual notifications as read
        - [ ] Users can mark all notifications as read
        - [ ] Notification preferences page in user settings
        - [ ] Mobile responsive design
        - [ ] Real-time updates using Supabase subscriptions

  - type: dropdown
    id: course_integration
    attributes:
      label: Course Integration
      description: Could this feature be part of a UIUC course project?
      options:
        - "Yes - CS 225 (Data Structures)"
        - "Yes - CS 411 (Database Systems)"
        - "Yes - CS 465 (User Interface Design)"
        - "Yes - CS 519 (Scientific Visualization)"
        - "Yes - BADM 350 (Foundations of Business)"
        - "Yes - Other course"
        - "No - Personal contribution"
        - "Not sure"

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples
      placeholder: |
        - Similar features in other platforms
        - Screenshots or mockups
        - Technical considerations
        - Timeline preferences

  - type: checkboxes
    id: development_approach
    attributes:
      label: Development Approach
      description: How would you like this feature to be developed?
      options:
        - label: I'd like @claude to help with planning and implementation
        - label: I want to work on this myself with guidance
        - label: I'm suggesting this for the team to consider

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Any other context or requirements?
      placeholder: |
        - Timeline considerations
        - Integration requirements
        - Design preferences
        
        Want AI implementation? Add: @claude please implement this feature

  - type: markdown
    attributes:
      value: |
        ---
        
        ### 🚀 Next Steps
        
        After submitting:
        1. The team will review your request
        2. If you mentioned @claude, you'll get AI assistance with planning
        3. We'll discuss implementation approach and timeline
        
        ### 🎓 For Students
        
        Feature contributions can be great for:
        - Building your development portfolio
        - Learning React, TypeScript, and modern web development
        - Contributing to open source projects