name: 🚀 Feature Request
description: Propose a new feature for IlliniHunt V2
title: "[FEATURE] "
labels: ["enhancement", "student-friendly"]
projects: ["vishalsachdev/illinihunt"]
assignees:
  - vishalsachdev

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to improve IlliniHunt! This template helps you create clear feature requests that can be implemented with AI assistance.
        
        💡 **Pro Tip**: Mention @claude in your description to get automatic implementation suggestions!

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: What feature would you like to see added?
      placeholder: "Add user notification system for new project submissions"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Problem Category
      description: What area does this feature improve?
      options:
        - Learning & Education Tools
        - Social & Communication
        - Productivity & Organization
        - Health & Wellness
        - Creative & Entertainment
        - Research & Data Analysis
        - Business & Entrepreneurship
        - Emerging Technology
        - Platform Infrastructure
        - User Experience
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve for UIUC students?
      placeholder: |
        Example: Students miss new project submissions in categories they're interested in. 
        They have to manually check the platform frequently to stay updated.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Example: Add a notification bell icon in the header that shows:
        - New projects in bookmarked categories
        - Comments on projects you've voted on
        - Replies to your comments
        
        Users should be able to:
        - Mark notifications as read
        - Configure notification preferences
        - Get email summaries (optional)
    validations:
      required: true

  - type: dropdown
    id: user_type
    attributes:
      label: Target Users
      description: Who would benefit from this feature?
      multiple: true
      options:
        - Students (undergraduate)
        - Students (graduate)
        - Faculty
        - Staff
        - External visitors
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature is?
      options:
        - 🟢 Simple (UI changes, small components)
        - 🟡 Moderate (new components, database changes)
        - 🔴 Complex (major features, architecture changes)
        - 🤔 Not sure
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What needs to be done for this feature to be complete?
      placeholder: |
        - [ ] Notification bell icon appears in header for authenticated users
        - [ ] Badge shows unread notification count
        - [ ] Dropdown shows recent notifications with timestamps
        - [ ] Users can mark individual notifications as read
        - [ ] Users can mark all notifications as read
        - [ ] Notification preferences page in user settings
        - [ ] Mobile responsive design
        - [ ] Real-time updates using Supabase subscriptions

  - type: dropdown
    id: course_integration
    attributes:
      label: Course Integration
      description: Could this feature be part of a UIUC course project?
      options:
        - "Yes - CS 225 (Data Structures)"
        - "Yes - CS 411 (Database Systems)"
        - "Yes - CS 465 (User Interface Design)"
        - "Yes - CS 519 (Scientific Visualization)"
        - "Yes - BADM 350 (Foundations of Business)"
        - "Yes - Other course"
        - "No - Personal contribution"
        - "Not sure"

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples
      placeholder: |
        - Similar features in other platforms
        - Screenshots or mockups
        - Technical considerations
        - Timeline preferences

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Are you interested in working on this feature?
      options:
        - label: I'd like to work on this feature myself
        - label: I'd like to collaborate with others on this
        - label: I'd like @claude to help implement this
        - label: I'm proposing this for someone else to implement

  - type: markdown
    attributes:
      value: |
        ---
        
        ### 🤖 AI Assistant Integration
        
        Want AI help with this feature? Try these commands:
        
        ```
        @claude analyze this feature request and suggest an implementation approach
        
        @claude create a technical specification for this notification system
        
        @claude implement the basic notification bell component with TypeScript
        ```
        
        ### 📚 For Students
        
        This feature request could be perfect for:
        - Course projects requiring real-world application development
        - Research on user engagement and notification systems
        - Portfolio development for internship/job applications
        - Learning modern React, TypeScript, and real-time systems